Initial changes for graviton smoke tests

diff --git a/.github/workflows/graviton-build-test-push-workflow.yml b/.github/workflows/graviton-build-test-push-workflow.yml
--- a/.github/workflows/graviton-build-test-push-workflow.yml
+++ b/.github/workflows/graviton-build-test-push-workflow.yml
@@ -1,12 +1,11 @@
-name: UBI Graviton Build and Test
+name: Build and Test
 on:
   push:
     branches:
-      - feature**
-      - graviton-sok
+      - CSPL_2920
 jobs:
   check-formating:
-    runs-on: macos-14
+    runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Dotenv Action
@@ -21,7 +20,7 @@ jobs:
     - name: Lint source code
       run: make vet && if [[ $? -ne 0 ]]; then false; fi
   #unit-tests:
-  #  runs-on: macos-14
+  #  runs-on: ubuntu-latest
   #  needs: check-formating
   #  steps:
   #    - uses: actions/checkout@v2
@@ -45,19 +44,22 @@ jobs:
   #    - name: Run Code Coverage
   #      run: goveralls -coverprofile=coverage.out -service=circle-ci -repotoken ${{ secrets.COVERALLS_TOKEN }}
   #    - name: Upload Coverage artifacts
-  #      uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2
+  #      uses: actions/upload-artifact@v4.4.0
   #      with:
   #        name: coverage.out
   #        path: coverage.out
-  build-graviton-operator-image:
+  build-operator-image:
     runs-on: ubuntu-latest
-    needs: check-formating
+    #needs: unit-tests
     env:
       SPLUNK_ENTERPRISE_IMAGE: ${{ secrets.SPLUNK_ENTERPRISE_IMAGE }}
       SPLUNK_OPERATOR_IMAGE_NAME: splunk/splunk-operator
       ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
       S3_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
     steps:
+    - name: Set up cosign
+      uses: sigstore/cosign-installer@main
+
     - uses: actions/checkout@v2
     - name: Dotenv Action
       id: dotenv
@@ -88,35 +90,97 @@ jobs:
     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1
-    - name: Make Splunk Operator Image and Push to ECR
+    - name: Build and push Splunk Operator Image
       run: |
-        docker buildx build --push --platform linux/arm64,linux/amd64 --tag ${{ secrets.ECR_REPOSITORY }}/${{ env.SPLUNK_OPERATOR_IMAGE_NAME }}:ubi-$GITHUB_SHA -f Dockerfile.ubi .
+        export PLATFORMS=linux/arm64
+        export BUILDPLATFORM=linux/arm64
+        export TARGETOS=linux
+        export TARGETARCH=arm64
+        export TARGET_OS_IMAGE=public.ecr.aws/amazonlinux/amazonlinux:2023.0.20211014
+        docker buildx build --push --platform=linux/arm64,linux/amd64 --tag ${{ secrets.ECR_REPOSITORY }}/${{ env.SPLUNK_OPERATOR_IMAGE_NAME }}:$GITHUB_SHA -f Dockerfile.graviton .
+    - name: Sign Splunk Operator image with a key
+      run: |
+        cosign sign --yes --key env://COSIGN_PRIVATE_KEY  ${{ secrets.ECR_REPOSITORY }}/${{ env.SPLUNK_OPERATOR_IMAGE_NAME }}:${{ github.sha }}
+      env:
+        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
+        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
+  vulnerability-scan:
+    permissions:
+      actions: read
+      contents: read
+      security-events: write
+    runs-on: ubuntu-latest
+    needs: build-operator-image
+    env:
+      SPLUNK_ENTERPRISE_IMAGE: ${{ secrets.SPLUNK_ENTERPRISE_IMAGE }}
+      SPLUNK_OPERATOR_IMAGE_NAME: splunk/splunk-operator
+      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
+      S3_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
+      IMAGE_NAME: ${{ secrets.ECR_REPOSITORY }}/splunk/splunk-operator:${{ github.sha }}
+    steps:
+    - name: Set up cosign
+      uses: sigstore/cosign-installer@main
+    - uses: actions/checkout@v2
+    - name: Dotenv Action
+      id: dotenv
+      uses: falti/dotenv-action@d4d12eaa0e1dd06d5bdc3d7af3bf4c8c93cb5359
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v2.5.0
+    - name: Configure AWS credentials
+      uses: aws-actions/configure-aws-credentials@v1
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+
+    - name: Login to Amazon ECR
+      uses: aws-actions/amazon-ecr-login@v1
+    - name: Pull Splunk Operator Image Locally
+      run: |
+        docker pull ${{ env.IMAGE_NAME }}
+    - name: Verify Signed Splunk Operator image 
+      run: |
+        cosign verify --key env://COSIGN_PUBLIC_KEY  ${{ env.IMAGE_NAME }}
+      env:
+        COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
+    - name: Run Trivy vulnerability scanner
+      uses: aquasecurity/trivy-action@master
+      with:
+        image-ref: '${{ env.IMAGE_NAME }}'
+        format: sarif
+        #exit-code: 1
+        severity: 'CRITICAL'
+        ignore-unfixed: true
+        output: 'trivy-results.sarif'
+    - name: Upload Trivy scan results to GitHub Security tab
+      uses: github/codeql-action/upload-sarif@v3
+      with:
+        sarif_file: 'trivy-results.sarif'
   smoke-tests:
-    needs: build-graviton-operator-image
+    needs: vulnerability-scan
     strategy:
       fail-fast: false
       matrix:
         test: [
                 basic,
-                appframeworks1,
-                managerappframeworkc3,
-                managerappframeworkm4,
-                managersecret,
-                managermc,
-                ]
+                #appframeworks1,
+                #managerappframeworkc3,
+                #managerappframeworkm4,
+                #managersecret,
+                #managermc,
+               ]
     runs-on: ubuntu-latest
     env:
       CLUSTER_NODES: 1
       CLUSTER_WORKERS: 3
-      SPLUNK_ENTERPRISE_IMAGE: ${{ secrets.SPLUNK_ENTERPRISE_IMAGE }}
-      SPLUNK_ENTERPRISE_RELEASE_IMAGE: ${{ secrets.SPLUNK_ENTERPRISE_RELEASE_IMAGE }}
+      SPLUNK_ENTERPRISE_IMAGE: ${{ secrets.SPLUNK_ENTERPRISE_IMAGE_GRAVITON }}
+      SPLUNK_ENTERPRISE_RELEASE_IMAGE: ${{ secrets.SPLUNK_ENTERPRISE_IMAGE_GRAVITON }}
       SPLUNK_OPERATOR_IMAGE_NAME: splunk/splunk-operator
       SPLUNK_OPERATOR_IMAGE_FILENAME: splunk-operator
       TEST_FOCUS: "${{ matrix.test }}"
       # This regex matches any string not containing smoke keyword
       TEST_TO_SKIP: "^(?:[^s]+|s(?:$|[^m]|m(?:$|[^o]|o(?:$|[^k]|k(?:$|[^e])))))*$"
       TEST_CLUSTER_PLATFORM: eks
-      EKS_INSTANCE_TYPE: m5.2xlarge
       EKS_VPC_PRIVATE_SUBNET_STRING: ${{ secrets.EKS_VPC_PRIVATE_SUBNET_STRING }}
       EKS_VPC_PUBLIC_SUBNET_STRING: ${{ secrets.EKS_VPC_PUBLIC_SUBNET_STRING }}
       TEST_BUCKET: ${{ secrets.TEST_BUCKET }}
@@ -168,7 +232,7 @@ jobs:
           DESIRED_VERSION=v3.8.2 bash get_helm.sh
       - name: Install EKS CTL
         run: |
-          curl --silent --insecure --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
+          curl --silent --insecure --location "https://github.com/weaveworks/eksctl/releases/download/${{ steps.dotenv.outputs.EKSCTL_VERSION }}/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
           sudo mv /tmp/eksctl /usr/local/bin
           eksctl version
       - name: Set up Docker Buildx
@@ -182,6 +246,11 @@ jobs:
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN}}
+      - name: Set Splunk Operator image
+        run: |
+            echo "SPLUNK_OPERATOR_IMAGE=${{ env.SPLUNK_OPERATOR_IMAGE_NAME }}:$GITHUB_SHA" >> $GITHUB_ENV
+      - name: Pull Splunk Enterprise Image
+        run: docker pull ${{ env.SPLUNK_ENTERPRISE_IMAGE }}
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
@@ -191,35 +260,34 @@ jobs:
       - name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v1
+      - name: Tag and Push Splunk Enterprise Image to ECR
+        run: |
+          docker tag ${{ env.SPLUNK_ENTERPRISE_IMAGE }} ${{ secrets.ECR_REPOSITORY }}/${{ env.SPLUNK_ENTERPRISE_IMAGE }}
+          docker push ${{ secrets.ECR_REPOSITORY }}/${{ env.SPLUNK_ENTERPRISE_IMAGE }}
       - name: Create EKS cluster
         run: |
-            export EKS_CLUSTER_K8_VERSION=${{ steps.dotenv.outputs.EKS_CLUSTER_K8_VERSION }}
-            export PLATFORMS=linux/arm64
-            export BUILDPLATFORM=linux/arm64
-            export TARGETOS=linux
-            export TARGETARCH=arm64
-            export EKS_INSTANCE_TYPE=c6g.4xlarge
-            make cluster-up
+           export EKS_CLUSTER_K8_VERSION=${{ steps.dotenv.outputs.EKS_CLUSTER_K8_VERSION }}
+           export PLATFORMS=linux/arm64
+           export BUILDPLATFORM=linux/arm64
+           export TARGETOS=linux
+           export TARGETARCH=arm64
+           export TARGET_OS_IMAGE=public.ecr.aws/amazonlinux/amazonlinux:2023.0.20211014
+           export EKS_INSTANCE_TYPE=${{ steps.dotenv.outputs.EKS_INSTANCE_TYPE_GRAVITON }}
+           make cluster-up
       - name: install metric server
         run: |
           kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
       - name: install k8s dashboard
         run: |
           kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.5/aio/deploy/recommended.yaml
-      #- name: Setup Kustomize
-      #  run: |
-      #    sudo snap install kustomize
-      #    mkdir -p ./bin
-      #    cp /snap/bin/kustomize ./bin/kustomize
-      - name: Install Kustomize
-        uses: multani/action-setup-kustomize@v1
-        with:
-          version: 4.5.4
+      - name: Setup Kustomize
+        run: |
+          sudo snap install kustomize
+          mkdir -p ./bin
+          cp /snap/bin/kustomize ./bin/kustomize
       - name: Run smoke test
         id: smoketest
         run: |
-          export SPLUNK_OPERATOR_IMAGE_GRAVITON=${{ secrets.ECR_REPOSITORY }}/${{ env.SPLUNK_OPERATOR_IMAGE_NAME }}:ubi-$GITHUB_SHA
-          export SPLUNK_ENTERPRISE_IMAGE_GRAVITON=${{ secrets.ECR_REPOSITORY }}/${{ steps.dotenv.outputs.SPLUNK_ENTERPRISE_RELEASE_IMAGE }}
           make int-test
       - name: Collect Test Logs
         if: ${{ always() }}
@@ -228,7 +296,7 @@ jobs:
           find ./test -name "*.log" -exec cp {} /tmp/pod_logs \;
       - name: Archive Pod Logs
         if: ${{ always() }}
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v4.4.0
         with:
           name: "splunk-pods-logs--artifacts-${{ matrix.test }}"
           path: "/tmp/pod_logs/**"
@@ -241,6 +309,13 @@ jobs:
         if: ${{ always() }}
         run: |
           make cluster-down
+      #- name: Test Report
+      #  uses: dorny/test-reporter@v1
+      #  if: success() || failure()    # run this step even if previous step failed
+      #  with:
+      #    name: Integration Tests          # Name of the check run which will be created
+      #    path: inttest-*.xml         # Path to test results
+      #    reporter: jest-junit        # Format of test results
   push-latest:
     needs: smoke-tests
     if: github.ref == 'refs/heads/main'
@@ -269,6 +344,9 @@ jobs:
         aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
     - name: Login to Amazon ECR
       uses: aws-actions/amazon-ecr-login@v1
-    - name: Pull Splunk Operator Image Locally and Push to docker hub
+    - name: Re-tag Splunk Operator Image
       run: |
-        docker buildx build --push --platform linux/arm64,linux/amd64 --tag ${{ env.SPLUNK_OPERATOR_IMAGE_NAME }}:ubi-${{ env.TAG }} -f Dockerfile.ubi .
+        docker pull ${{ secrets.ECR_REPOSITORY }}/${{ env.SPLUNK_OPERATOR_IMAGE_NAME }}:$GITHUB_SHA
+        docker buildx imagetools create -t ${{ env.SPLUNK_OPERATOR_IMAGE_NAME }}:${{ env.TAG }} ${{ secrets.ECR_REPOSITORY }}/${{ env.SPLUNK_OPERATOR_IMAGE_NAME }}:$GITHUB_SHA
+    - name: Push Splunk Operator Image to Docker Hub
+      run: docker push ${{ env.SPLUNK_OPERATOR_IMAGE_NAME }}:${{ env.TAG }}
